setwd("/Users/Rodrigo/Documents/Pos_doc/IdeaS/Immunobase/proceed_data/")
ds <- read.delim("mirnas_per_diseases.txt", header = T)
head(ds)
colnames(ds)

intersect(ds$CEL, ds$CRO)
intersect(ds$CEL, ds$JIA)
intersect(ds$CEL, ds$MS)
intersect(ds$CEL, ds$PBC)
intersect(ds$CEL, ds$RA)
intersect(ds$CEL, ds$SLE)
intersect(ds$CEL, ds$T1D)
intersect(ds$CEL, ds$UC)
intersect(ds$CRO, ds$JIA)
intersect(ds$CRO, ds$MS)
intersect(ds$CRO, ds$PBC)
intersect(ds$CRO, ds$RA)
intersect(ds$CRO, ds$SLE)
intersect(ds$CRO, ds$T1D)
intersect(ds$CRO, ds$UC)
intersect(ds$T1D, ds$JIA)
intersect(ds$T1D, ds$MS)
intersect(ds$T1D, ds$PBC)
intersect(ds$T1D, ds$RA)
